---
abstract: 'Wrap any simple class as a service for Dancer2'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0.19
  HTTP::Tiny: 0
  JSON: 0
  LWP::UserAgent: 0
  List::Util: 0
  Test::More: 0.96
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Adapter
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  Dancer2::Plugin::Adapter:
    file: lib/Dancer2/Plugin/Adapter.pm
    version: 0.005
recommends:
  Class::Load::XS: 0
requires:
  Class::Load: 0
  Dancer2: 0
  Dancer2::Plugin: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/dagolden/dancer2-plugin-adapter/issues
  homepage: https://metacpan.org/release/Dancer2-Plugin-Adapter
  repository: git://github.com/dagolden/dancer2-plugin-adapter.git
version: 0.005
x_contributors:
  - 'Blabos de Blebe <blabos@blabos.org>'
